### ISSUE TITLE
Converts empty RMC values for variation into invalid 0.0 result

### ISSUE THREAD

**Issue by davidsanner** [SignalK/nmea0183-utilities#18]
If RMC is missing fields I would think those values should not be set to 0.0 and either set to null or not set.

eg. navigation.variation should not be set to 0.0 if RMC sentence is missing either of the two required values.  
I'm having the issue w/ downstream apps/plugins displaying magnetic / true north incorrectly.

I could do a PR if that would help

**Comment by tkurki** [comment]
I think this should be fixed in RMC, not globally in this package.

**Comment by davidsanner** [comment]
Thanks... makes sense.  Prob several of the sentences need updating but I started with RMC
https://github.com/SignalK/nmea0183-signalk/pull/216

RMC will now return null for missing lat/long/cog/sog/variation as noted here:
https://github.com/SignalK/specification/blob/c446914b331084dc5c8bcddf6aa65003b69b1c45/gitbook-docs/data_model.md#missing-or-invalid-data
