### ISSUE TITLE
Consider utilizing unit conversion package

### ISSUE THREAD

**Issue by webmasterkai** [SignalK/nmea0183-utilities#7]
Much of what is in the package can be found elsewhere in conversion specific packages. One example is [convert-units](https://github.com/ben-ng/convert-units). It's setup in a way where it's easy to add additional conversions. I have a [pull request](https://github.com/ben-ng/convert-units/pull/96) in for some nautical units.

**Comment by tkurki** [comment]
This package contains the necessary utility functions for nmea related stuff. I don't think replacing the small number of conversion constants with a unit conversion library would be a better solution.
